# Generated by Django 4.1.7 on 2023-05-09 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_clientes_tipo_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='telefono2',
            field=models.CharField(default='', max_length=15, null=True),
        ),
    ]
