# Generated by Django 4.1.7 on 2023-05-16 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basedata', '0002_formularios_saq'),
        ('clientes', '0004_alter_certificados_codigo_certificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificados',
            name='formularios_saq',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='basedata.formularios_saq'),
        ),
    ]
