# Generated by Django 4.1.7 on 2023-04-28 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='paises',
            fields=[
                ('id_pais', models.AutoField(primary_key=True, serialize=False)),
                ('pais', models.CharField(max_length=200, verbose_name='pais')),
            ],
        ),
        migrations.CreateModel(
            name='versiones_norma',
            fields=[
                ('id_version_norma', models.AutoField(primary_key=True, serialize=False)),
                ('version_norma', models.CharField(max_length=200, verbose_name='version_norma')),
                ('estado_version_norma', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='departamentos',
            fields=[
                ('id_departamento', models.AutoField(primary_key=True, serialize=False)),
                ('departamento', models.CharField(max_length=200, verbose_name='departamento')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basedata.paises')),
            ],
        ),
        migrations.CreateModel(
            name='ciudades',
            fields=[
                ('id_ciudad', models.AutoField(primary_key=True, serialize=False)),
                ('ciudad', models.CharField(max_length=200, verbose_name='ciudad')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basedata.departamentos')),
            ],
        ),
    ]
