# Generated by Django 4.1.7 on 2023-05-16 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basedata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='formularios_saq',
            fields=[
                ('id_formulario_saq', models.AutoField(primary_key=True, serialize=False)),
                ('formulario_saq', models.CharField(max_length=30, verbose_name='formulario_saq')),
                ('estado_formulario_saq', models.CharField(max_length=15)),
            ],
        ),
    ]
